"""consent_logs table

Revision ID: 9760c0c7d447
Revises: 7b789ad8c131
Create Date: 2025-08-23 21:17:32.189820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9760c0c7d447'
down_revision = '7b789ad8c131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('consent_text', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consent_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consent_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consent_logs_user_id'))

    op.drop_table('consent_logs')
    # ### end Alembic commands ###
