"""scans table

Revision ID: aab0acc3fb33
Revises: 7a52c5320878
Create Date: 2025-08-23 16:24:22.821966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab0acc3fb33'
down_revision = '7a52c5320878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('target_ip', sa.String(length=45), nullable=True),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('scan_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scan_config', sa.Text(), nullable=True),
    sa.Column('total_vulnerabilities', sa.Integer(), nullable=False),
    sa.Column('high_severity_count', sa.Integer(), nullable=False),
    sa.Column('medium_severity_count', sa.Integer(), nullable=False),
    sa.Column('low_severity_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_user_id'))
        batch_op.drop_index(batch_op.f('ix_scans_status'))

    op.drop_table('scans')
    # ### end Alembic commands ###
