"""vulnerabilities table

Revision ID: dde3ae69814c
Revises: 562af8eae0f8
Create Date: 2025-08-23 17:01:47.966675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde3ae69814c'
down_revision = '562af8eae0f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('tool_result_id', sa.Integer(), nullable=True),
    sa.Column('vuln_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_url', sa.String(length=500), nullable=True),
    sa.Column('affected_parameter', sa.String(length=100), nullable=True),
    sa.Column('cve_id', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('false_positive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['tool_result_id'], ['tool_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vulnerabilities_scan_id'), ['scan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vulnerabilities_severity'), ['severity'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_severity'))
        batch_op.drop_index(batch_op.f('ix_vulnerabilities_scan_id'))

    op.drop_table('vulnerabilities')
    # ### end Alembic commands ###
